agenda_pericias/urls.py
from django.urls import path
from app_agenda_pericias import views

urlpatterns = [
    path('', views.index, name='index,'),
    path('home/', views.home, name='home'),
    path('verificar_cpf/', views.verificar_cpf, name='verificar_cpf'),
    path('verificar_perito/', views.verificar_perito, name='verificar_perito'),    
    path('agenda_pericias/', views.agendar_pericias , name='agendar_pericias'),
    path('listagem/', views.listagem_pericias , name='listagem_pericias'),
    path('listagem_pericias/', views.listagem_completa_pericias , name='listagem_completa_pericias'),
    path('editar_pericia/<int:id>', views.editar_pericia, name='editar_pericia'),
    path('editar_listagem_pericia/<int:id>', views.editar_listagem_pericia, name='editar_listagem_pericia'),
    path('confirmacao/',views.confirmacao, name='confirmacao'),
    path("atualizar_comparecimento/", views.atualizar_comparecimento, name="atualizar_comparecimento"),
    path("atualizar_comparecimento_1/", views.atualizar_comparecimento_1, name="atualizar_comparecimento_1"),
    path('atualizar/<int:id>/', views.atualizar_saida_pericia, name='atualizar_saida_pericia'),
    path('login/', views.login, name='login'),
    path('import_excel/', views.import_excel , name='import_excel'),
    path('logout/', views.user_logout , name='logout'),
    path('pericias-por-especialidade/', views.pericias_por_especialidade, name='pericias_por_especialidade'),
    path('pericias-nao-realizadas/', views.pericias_nao_realizadas, name='pericias_nao_realizadas'),    
    path('pericias-por-perito/', views.pericias_por_perito, name='pericias_por_perito'),
    path('agendamento-por-tipo/', views.agendamentos_por_tipo , name='agendamento_por_tipo'),
    path('peritos/', views.listar_peritos, name='listar_peritos'),
    path('relatorio/', views.relatorio_pericias, name='relatorio_pericias'),
    path('relatorio_perito/', views.listagem_pericias_por_perito_mes, name='listagem_pericias_por_perito_mes'),
    path('gerar_pdf/', views.gerar_pdf, name='gerar_pdf'),    
    path('gerar_pdf_perito/', views.gerar_pdf_perito, name='gerar_pdf_perito'),    
    path('listagem_por_perito/', views.listagem_pericias_por_perito, name='listagem_pericias_por_perito'),    
    path('atualiza/', views.atualizar_registros_pericias, name='atualizar_registros_pericias'),
    path('enviar_pauta/', views.enviar_pauta_view, name='enviar_pauta'),    
]

app_agenda_pericias/models.py
from django.db import models
from django.contrib.auth.hashers import make_password

class tbl_pericias_agendadas(models.Model):
    data_pericia = models.CharField(max_length=20, blank=True, null=True)
    jurisdicao = models.CharField(max_length=100, blank=True, null=True)
    perito = models.CharField(max_length=100, blank=True, null=True)
    periciado = models.CharField(max_length=100, blank=True, null=True)
    cpf_parte = models.CharField(max_length=14, blank=True, null=True)
    processo = models.CharField(max_length=100, blank=True, null=True)
    especialidade = models.CharField(max_length=100, blank=True, null=True)
    situacao_pericia = models.CharField(max_length=100, blank=True, null=True)
    compareceu_pericia = models.BooleanField(default=False)
    hora_entrada = models.TimeField()
    hora_saida = models.TimeField()
    usuario = models.CharField(max_length=50, blank=True, null=True)
    data_marcada = models.DateField(blank=True, null=True)
    hora_marcada = models.TimeField(blank=True, null=True)
    
    class Meta:
        db_table = 'tbl_pericias_agendadas'
        unique_together = ('periciado', 'processo', 'data_pericia', 'situacao_pericia')
        indexes = [
            models.Index(fields=['periciado', 'processo', 'data_pericia', 'situacao_pericia']),
        ]

    def __str__(self):
        return f'{self.periciado} - {self.processo} - {self.data_pericia} - {self.situacao_pericia}'

class tbl_usuarios(models.Model):
    cpf = models.CharField(max_length=11, blank=True, null=True)
    nome = models.CharField(max_length=150, blank=True, null=True)
    usuario = models.CharField(max_length=50)
    senha = models.CharField(max_length=128)  # aumenta o tamanho por segurança
    unidade = models.CharField(max_length=3, blank=True, null=True)
    perito = models.BooleanField(blank=True, null=True)
    email = models.CharField(max_length=150, blank=True, null=True)

    class Meta:
        db_table = 'tbl_usuarios'

    def save(self, *args, **kwargs):
        # Criptografa a senha apenas se ela ainda não estiver criptografada
        if not self.senha.startswith('pbkdf2_'):
            self.senha = make_password(self.senha)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.nome

class tbl_unidades(models.Model):
    subsecao = models.CharField(max_length=100)

    class Meta:
        db_table = 'tbl_unidades'

    def __str__(self):
        return self.subsecao
    
class tbl_salas(models.Model):
    sala = models.CharField(max_length=25, blank=True, null=True)
    perito = models.CharField(max_length=3, blank=True, null=True)

    class Meta:
        db_table = 'tbl_salas'

class tbl_peritos(models.Model):
    cpf = models.CharField(max_length=11, blank=True, null=True)
    nome_perito = models.CharField(max_length=150, blank=True, null=True)

    class Meta:
        db_table = 'tbl_peritos'

app_agenda_pericias/views.py
from .utils import enviar_pauta_peritos
from pyexpat.errors import messages
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from .models import tbl_pericias_agendadas, tbl_unidades, tbl_usuarios, tbl_peritos
from .forms import agendar_pericias_form, cadastro_usuario_form, login_form, editar_pericia_form
from django.utils import timezone
from datetime import datetime, timedelta
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from .context_processors import variaveis_globais
from openpyxl import load_workbook
import logging, json
from django.db.utils import IntegrityError
from django.http import JsonResponse, HttpResponse, FileResponse
from django.db.models import Count, Sum
from django.db.models.functions import TruncMonth
from django.db import transaction
from django.conf import settings
import os
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph
from django.core.mail import send_mail
from django.utils.timezone import now
from django.urls import reverse
from django.utils.http import urlencode
from django.contrib.auth.hashers import check_password
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.hashers import make_password

logger = logging.getLogger(__name__)

# logar e autentica na aplicação
def login_form(request):
    if request.method == 'POST':
        cpf = request.POST.get('cpf')
        senha_digitada = request.POST.get('senha')

        try:
            usuario = tbl_usuarios.objects.get(cpf=cpf)
        except usuario.DoesNotExist:
            return render(request, 'login.html', {'erro': 'CPF não encontrado.'})

        # Verifica se a senha digitada bate com a senha criptografada
        if check_password(senha_digitada, usuario.senha):
            request.session['usuario_id'] = usuario.id
            request.session['usuario_nome'] = usuario.nome
            return redirect('home')  # ajuste para sua rota
        else:
            return render(request, 'agenda_pericias/erro_login.html', {'erro': 'Senha incorreta.'})

    foruns = tbl_unidades.objects.all().order_by('subsecao')
    return render(request, 'agenda_pericias/index.html',{'foruns':foruns})

def login(request):
    if request.method == 'POST':
        cpf_login = request.POST.get('cpf_login')
        senha_digitada = request.POST.get('senha_login')
        unidade = request.POST.get('unidade_login')

        try:
            usuario = tbl_usuarios.objects.get(cpf=cpf_login)
        except tbl_usuarios.DoesNotExist:
            return render(request, 'login.html', {'erro': 'CPF não encontrado.'})

        # Verifica se a senha digitada bate com a senha criptografada
        if check_password(senha_digitada, usuario.senha):
            # Armazena dados do usuário na sessão
            request.session['usuario_id'] = usuario.id
            request.session['unidade'] = unidade

            # Define as permissões dos menus conforme o perfil do usuário
            menus = {
                'disable_pericias': usuario.perito,  # True se for perito
                'disable_informacoes': usuario.perito,                
                'disable_atualizar': usuario.perito,
                'disable_area_perito': not usuario.perito,  # True se não for perito
            }
            # Redireciona para home com o contexto (sem quebrar fluxo atual)
            return render(request, 'agenda_pericias/home.html')

        else:
            return render(request, 'agenda_pericias/erro_login.html', {'erro': 'Senha incorreta.'})

    # Se for GET, exibe página inicial com dropdowns de fóruns
    foruns = tbl_unidades.objects.all().order_by('subsecao')
    return render(request, 'agenda_pericias/index.html', {'foruns': foruns})

def verificar_perito(request):
    """Verifica se o CPF digitado pertence a um perito"""
    cpf = request.GET.get('cpf_login')
    if not cpf:
        return JsonResponse({'erro': 'CPF não informado'}, status=400)
    try:
        usuario = tbl_usuarios.objects.get(cpf=cpf)
        return JsonResponse({'is_perito': bool(usuario.perito)})
    except tbl_usuarios.DoesNotExist:
        return JsonResponse({'is_perito': False})    

def user_logout(request):
    logout(request)
    messages.success(request, "Você foi desconectado com sucesso.")
    return render(request, 'agenda_pericias/index.html')

# Cadastro de usuário
def index(request):
    foruns = tbl_unidades.objects.all().order_by('subsecao')

    if request.method == 'POST':
        form = cadastro_usuario_form(request.POST, request.FILES)

        if form.is_valid():
            cpf_ = form.cleaned_data['cpf']
            subsecao_ = form.cleaned_data['unidade']

            # 🔍 Verifica duplicidade
            if tbl_usuarios.objects.filter(cpf=cpf_, unidade=subsecao_).exists():
                messages.error(request, 'Usuário já cadastrado.')
                return render(request, 'agenda_pericias/index.html', {'foruns': foruns})

            # 🔍 Busca na tabela de peritos
            perito_data = tbl_peritos.objects.filter(cpf=cpf_).first()

            # Cria o objeto usuário sem salvar ainda
            usuario = form.save(commit=False)

            # Define campos adicionais
            usuario.usuario = usuario.nome.split()[0] if usuario.nome else cpf_

            if perito_data:
                usuario.perito = True
                usuario.nome = perito_data.nome_perito
            else:
                usuario.perito = False

            # Garante que a senha será criptografada
            usuario.senha = make_password(usuario.senha)

            # 🔥 Tenta salvar
            try:
                usuario.save()
                messages.success(request, 'Usuário cadastrado com sucesso.')
            except Exception as e:
                messages.error(request, f'Erro ao salvar usuário: {e}')
                print(f"[ERRO SAVE] {e}")  # Log no terminal

            return render(request, 'agenda_pericias/index.html', {'foruns': foruns})  # Recarrega a página limpa

        else:
            # 🔍 Mostra erros de validação do formulário
            messages.error(request, f'Erro no formulário: {form.errors}')
            print(f"[FORM ERROR] {form.errors}")

            return render(request, 'agenda_pericias/index.html', {'foruns': foruns})

    # GET
    return render(request, 'agenda_pericias/index.html', {'foruns': foruns})

@csrf_exempt
def verificar_cpf(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        cpf = data.get('cpf')

        # Verifica se já existe o usuário
        if tbl_usuarios.objects.filter(cpf=cpf).exists():
            return JsonResponse({'existe_usuario': True})

        # Verifica se o CPF consta em tbl_peritos
        perito = tbl_peritos.objects.filter(cpf=cpf).first()
        if perito:
            return JsonResponse({
                'existe_usuario': False,
                'encontrado_perito': True,
                'nome_perito': perito.nome_perito
            })

        # Caso não encontre em nenhuma tabela
        return JsonResponse({
            'existe_usuario': False,
            'encontrado_perito': False
        })        

# Página inicial
def home(request):
    # Redireciona para a página de listagem de pericias filtradas
    return render(request, 'agenda_pericias/home.html')

# Página de informações
def confirmacao(request):
    return render(request, 'agenda_pericias/confirmacao.html')

# Agendar de pericias
def agendar_pericias(request):
    if request.method == "POST":
        form = agendar_pericias_form(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Perícia agendada com sucesso.')
        return render(request, "agenda_pericias/agendar_pericias.html")
    else:
        peritos = tbl_peritos.objects.all().order_by('nome_perito')
        return render(request, "agenda_pericias/agendar_pericias.html", {'peritos': peritos})

# Página com a relação de pericias agendadas
def listagem_pericias(request):
    context_globals = variaveis_globais(request)
    jurisdicao = context_globals['subsecao']
    dia_atual = datetime.now().strftime('%d/%m/%Y')
    pericias = tbl_pericias_agendadas.objects.filter(situacao_pericia__icontains='Designada', jurisdicao__icontains=jurisdicao, data_pericia__icontains=dia_atual).exclude(especialidade__icontains='Social').order_by('data_marcada','hora_marcada')

    busca = request.GET.get('perito')
    busca1 = request.GET.get('processo')
    if busca:
        pericias = pericias.filter(perito__icontains=busca)
    if busca1:
        pericias = pericias.filter(processo__icontains=busca1)
    if busca and busca1:
        pericias = pericias.filter(perito__icontains=busca, processo__icontains=busca1)
    # Redireciona para a página de listagem de pericias filtradas
    return render(request, 'agenda_pericias/listagem_pericias.html', {'pericias': pericias})

def listagem_completa_pericias(request):
    context_globals = variaveis_globais(request)
    jurisdicao = context_globals['subsecao']
    pericias = tbl_pericias_agendadas.objects.filter(situacao_pericia__icontains='Designada', jurisdicao__icontains=jurisdicao).exclude(especialidade__icontains='Social').order_by('data_marcada', 'hora_marcada')

    busca = request.GET.get('search')
    if busca:
        pericias = pericias.filter(data_pericia__icontains=busca)
    # Redireciona para a página de listagem de pericias filtradas
    return render(request, 'agenda_pericias/listagem_completa_pericias.html', {'pericias': pericias})

def editar_pericia(request, id):
    pericias = tbl_pericias_agendadas.objects.get(id=id)
    if request.method == 'POST':

app_agenda_pericias/templates/agenda_pericias/confirmacao.html
{% extends 'agenda_pericias/base.html' %}
{% block content %}
<head>
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        .btn {
            padding: 10px 20px;
            margin-right: 10px;
            cursor: pointer;
            border: none;
            border-radius: 5px;
            background-color: #007bff;
            color: #fff;
        }

        .btn:hover {
            background-color: #0056b3;
        }
    </style>

</head>
<body>
    <h1>Informações de Cadastro</h1>
    <form method="post" href="{% url 'agendar_pericias' %}">
    {% csrf_token %}
        <table>
            <tr>
                <th>Data</th>
                <th>Perito</th>
                <th>Periciado</th>
                <th>CPF da Parte</th>
                <th>Processo</th>
                <th>Especialidade</th>
                <th>Situação da Perícia</th>
                <th>Compareceu?</th>
                <th>Hora Entrada</th>
                <th>Hora Saída</th>
            </tr>
            <tr>
                <td id="data_pericia"></td>
                <td id="perito"></td>
                <td id="periciado"></td>
                <td id="cpf_parte"></td>
                <td id="processo"></td>
                <td id="especialidade"></td>
                <td id="situacao_pericia"></td>
                <td id="compareceu_pericia"></td>
                <td id="hora_entrada"></td>
                <td id="hora_saida"></td>

                <td>
                    <button class="btn" onclick="editarCadastro()">Editar</button>
                </td>
                <td>
                    <button class="btn" type="submit">Confirmar</button>
                </td>    
            </tr>
        </table>
    </form>    
    <script>
        // Recuperar as informações temporariamente armazenadas
        document.getElementById('data_pericia').textContent = localStorage.getItem('data_pericia');
        document.getElementById('perito').textContent = localStorage.getItem('perito');
        document.getElementById('periciado').textContent = localStorage.getItem('periciado');
        document.getElementById('processo').textContent = localStorage.getItem('processo');
        document.getElementById('especialidade').textContent = localStorage.getItem('especialidade');
        document.getElementById('situacao_pericia').textContent = localStorage.getItem('situacao_pericia');
        document.getElementById('hora_entrada').textContent = localStorage.getItem('hora_entrada');
        document.getElementById('hora_saida').textContent = localStorage.getItem('hora_saida');

        // Função para editar o cadastro (retornar para a tela de cadastro)
        function editarCadastro() {
            window.location.href = "{% url 'agendar_pericias' %}"; // Altere para o nome do arquivo da tela de cadastro
        }

        // Função para confirmar o cadastro (ir para a página de confirmação)
        function confirmarCadastro() {
                
                window.location.href="{% url 'listagem_pericias' %}";
        }
    </script>
</body>
{% endblock %}

app_agenda_pericias/templates/agenda_pericias/editar_listagem_pericia.html
{% extends 'agenda_pericias/base.html' %}
{% block content %}
{% load static %}

{% if messages %}
    <div class="alert alert-danger">
        {% for message in messages %}
            <p>{{ message }}</p>
        {% endfor %}
    </div>
{% endif %}

<head>
    <title>Editar Pedido</title>
    <style>
        .container {
            display: flex;
            justify-content: space-between;
        }
        .column {
            margin: 20px;
            padding: 20px;
            border: 1px solid #ccc;
            width: 20%;
        }
        .column label {
            display: block;
            margin-top: 10px;
        }
        .column input {
            width: 80%;
        }
    </style>
</head>
<h1 style="text-align: center; font-size: 25px; margin-top: 1%; color: black;">Atualização de Andamento</h1>
<div class="container" style="width: 65%;margin-left: 15%;">
    <table>
        <th>
            <a style="text-align: center; font-size: 20px; color: black;">Edição de Perícia</a>
        </th>    
    </table>
</div> 
<br>
<form method="POST">
	<div class="container" style="width: 65%;margin-left: 15%;">
        {% csrf_token %}
        <table class="table table-bordered table-striped" style="font-size: 15px; white-space: nowrap">
            <div style="margin: 20px 0;">
                <tr style="vertical-align: middle;"> 
                    <th hidden></th>
                    <th style="text-align: center;">Hora Entrada</th>
                    <th style="text-align: center;">Hora Saída</th>
                    <th></th>
                </tr>
                <tr tr style="font-size: 13px; line-height: 1px; text-rendering: auto; vertical-align: middle;">
                    <td hidden>{{ form.id }}</td>
                    <td style="text-align: center;">{{form.hora_entrada}}</td>
                    <td style="text-align: center;">{{form.hora_saida}}</td>
                    <td style="text-align: center; vertical-align: middle;">
                        <a>
                            <button type="submit" class="btn btn-primary btn-sm">Salvar/Voltar</button>
                        </a>
                    </td>
                </tr>
            </div>
        </table>
	</div>
</form>

<script>
    $(document).ready(function() {
        $('#id_hora_entrada, #id_hora_saida').mask('00:00'); 
    });
</script>
{% endblock %}

app_agenda_pericias/templates/agenda_pericias/listagem_pericias.html
{% extends 'agenda_pericias/base.html' %}
{% block content %}
{% load static %} <!-- Nova linha que carrega os arquivos estáticos -->  
<div class="container-fluid" style="padding-top: 5%; padding-bottom: 5%;">
    <h2 style="text-align: center; margin-top: 10px; font-size: 25px; color: black;">Perícias Agendadas do dia</h2>
    <br>    
    <form name="form_filtrar_pericias" id="formFiltrar" method="post">
        {% csrf_token %}
        <table class="table table-bordered table-striped" style="font-size: 15px; white-space: nowrap">
            <tr style="text-align:center; vertical-align: middle;">
                <td hidden>id</td>
                <th style="vertical-align: middle; text-align: center;">Data Perícia</th>
                <th style="vertical-align: middle; text-align: center;">Perito</th>
                <th style="vertical-align: middle; text-align: center;">Periciado</th>
                <th style="vertical-align: middle; text-align: center;">Processo</th>
                <th style="vertical-align: middle; text-align: center;">Especialidade</th>
                <th style="vertical-align: middle; text-align: center;">Situação</th>
                <th style="vertical-align: middle; text-align: center;">✔</th>
                <th style="vertical-align: middle; text-align: center;">Entrada</th>
                <th style="vertical-align: middle; text-align: center;">Saída</th>
                <th></th>
            </tr>
            {% for pericia in pericias %}
            <tr id="row-{{ pericia.id }}" style="font-size: 13px; line-height: 1px; text-rendering: auto; vertical-align: middle; {% if pericia.compareceu_pericia and pericia.hora_saida %} background-color: #ADD8E6; {% endif %}">
                <td hidden>{{ pericia.id }}</td>
                <td style="vertical-align: middle; text-align: center;">{{ pericia.data_pericia }}</td>
                <td style="vertical-align: middle;">{{ pericia.perito }}</td>
                <td style="vertical-align: middle;">{{ pericia.periciado }}</td>
                <td style="vertical-align: middle; text-align: center;">{{ pericia.processo }}</td>
                <td style="vertical-align: middle;">{{ pericia.especialidade }}</td>
                <td style="vertical-align: middle; text-align: center;">{{ pericia.situacao_pericia }}</td>
                <td style="vertical-align: middle; text-align: center;"><input type="checkbox" id="id_compareceu_pericia" name="compareceu_pericia" class="compareceu-checkbox" data-id="{{ pericia.id }}" {% if pericia.compareceu_pericia %}checked{% endif %}></td>
                <td style="vertical-align: middle; text-align: center;">{{ pericia.hora_entrada|date:"H:i" }}</td>
                <td style="vertical-align: middle; text-align: center;">{{ pericia.hora_saida|date:"H:i" }}</td>
                <td style="vertical-align: middle; text-align: center;">
                    <a href="{% url 'atualizar_saida_pericia' pericia.id %}">
                        {% if not pericia.compareceu_pericia %}
                        <img src="{% static 'images/lapis.png' %}" style="max-width: 15px; max-height: 15px; border: 0px;">
                        {% elif pericia.compareceu_pericia and not pericia.hora_saida %}
                        <img src="{% static 'images/sair.png' %}" style="max-width: 15px; max-height: 15px; border: 0px;">
                        {% elif pericia.compareceu_pericia and pericia.hora_entrada and pericia.hora_saida %}
                        <img src="{% static 'images/lapis.png' %}" style="max-width: 15px; max-height: 15px; border: 0px;">
                        {% endif %}
                    </a>
                </td>
            </tr>
            {% endfor %}
        </table>
    </form>
</div>

<footer>
    <form method="GET">
      <div position="fixed" class="container-fluid">
          <a style="text-decoration: none; color: white; font-size: small;">
            Perito: <input type="text" name="perito" id="perito" style="width: 120px; height: 25px; text-align: center; color: black; margin-right: 5px;">
            Processo: <input type="text" name="processo" id="processo" style="width: 190px; height: 25px; text-align: center; color: black;">
            <button class="btn btn-primary btn-sm" type="submit" id="button-addon1" style="margin-left: 5px;">Buscar/Limpar</button>
          </a>
      </div>
    </form>
</footer>

<script>
    $('#search').mask('00/00/0000');
    $('#processo').mask('0000000-00.0000.0.00.0000')
</script>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        document.querySelectorAll(".compareceu-checkbox").forEach(function(checkbox) {
            checkbox.addEventListener("change", function() {
                let periciaId = this.getAttribute("data-id");
                let status = this.checked ? 1 : 0;
                
                fetch("{% url 'atualizar_comparecimento' %}", {
                    method: "POST",
                    headers: {
                        "Content-Type": "application/json",
                        "X-CSRFToken": "{{ csrf_token }}"
                    },
                    body: JSON.stringify({ "id": periciaId, "compareceu": status })
                })
                .then(response => response.json())
                .then(data => {
                    if (data.success) {
                        console.log("Atualização realizada com sucesso!");
                        window.location.reload(); // Recarrega a página
                    } else {
                        console.error("Erro ao atualizar.");
                    }
                })
                .catch(error => console.error("Erro na requisição:", error));
            });
        });
    });
</script>
{% endblock %}

app_agenda_pericias/templates/agenda_pericias/listagem_pericias_por_perito.html
{% extends 'agenda_pericias/base.html' %}
{% block content %}
{% load static %} <!-- Nova linha que carrega os arquivos estáticos -->  
<div class="container-fluid" style="padding-top: 5%; padding-bottom: 5%;">
    {% if view_origem == 'dia' %}
        <h2 style="text-align: center; margin-top: 10px; font-size: 25px; color:black;">
            Perícias Agendadas do Dia
        </h2>
    {% elif view_origem == 'mes' %}
        <h2 style="text-align: center; margin-top: 10px; font-size: 25px; color:black;">
            Perícias Agendadas do Mês
        </h2>
    {% else %}
        <h2 style="text-align: center; margin-top: 10px; font-size: 25px; color:black;">
            Perícias Agendadas do Mês
        </h2>
    {% endif %}
    <form name="form_filtrar_pericias" id="formFiltrar" method="post">
        {% csrf_token %}
        <table class="table table-bordered table-striped" style="font-size: 15px; white-space: nowrap">
            <tr style="text-align:center; vertical-align: middle;">
                <td hidden>id</td>
                <th>Data Perícia</th>
                <th>Perito</th>
                <th>Periciado</th>
                <th>Processo</th>
                <th>Especialidade</th>
                <th>Situação</th>
                <th>Compareceu?</th>
                <th>Entrada</th>
                <th>Saída</th>
            </tr>
            {% for pericia in pericias %}
            <tr style="font-size: 13px; line-height: 1px; text-rendering: auto; vertical-align: middle;">
                <td hidden>{{ pericia.id }}</td>
                <td>{{ pericia.data_pericia }}</td>
                <td>{{ pericia.perito }}</td>
                <td>{{ pericia.periciado }}</td>
                <td>{{ pericia.processo }}</td>
                <td>{{ pericia.especialidade }}</td>
                <td>{{ pericia.situacao_pericia }}</td>
                <td style="text-align: center"><input type="checkbox" id="id_compareceu_pericia" name="compareceu_pericia" {% if pericia.compareceu_pericia %}checked{% endif %}></td>
                <td>{{ pericia.hora_entrada|date:"H:i" }}</td>
                <td>{{ pericia.hora_saida|date:"H:i" }}</td>
            </tr>
            {% endfor %}
        </table>
    </form>
</div>

<footer>
    <form method="GET">
      <div position="fixed" class="container-fluid">
          <a style="text-decoration: none; color: white; font-size: small;">
            <a style="text-decoration: none; color: white; font-size: small;">
                Data: <input type="text" placeholder="" name="search" id="search" style="width: 120px; height: 25px; text-align: center;color: black;">
                <button class="btn btn-primary btn-sm" type="submit" id="button-addon1">Buscar/Limpar</button>
              </a>
      </div>
    </form>
</footer>
{% endblock %}